server:
  port: 80

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 39141dfdfb0a3db9b33a9e9a074768e4
            client-secret: MNxc3DBzURHPXLk9ZcE3Ih0pEmFP5UWq
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  servlet:
    multipart:
      enabled: true
      location: /Users/jeong-yeob/Documents/kakaocloudlecture/spring/review/data
      max-file-size: 30MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

com:
  yeop:
    upload:
      path: /Users/jeong-yeob/Documents/kakaocloudlecture/spring/review/data


