server:
  port: 7070

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

